name: CI/CD prod-line-sys-svc

# Workflow triggers
on:
  push:
    branches:
      - main
      - svc/prod-line-sys-svc
      - svc/monitoring
    paths:
      - "milk-services/prod-line-sys/prod-line-sys-svc/**"
  pull_request:
    branches:
      - main
      - svc/prod-line-sys-svc
      - svc/monitoring
    paths:
      - "milk-services/prod-line-sys/prod-line-sys-svc/**"

# Environment Variables
env:
  IMAGE_NAME: prod-line-sys-svc # lower case

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # Authenticate with GitHub Container Registry, could be changed to use DockerHub
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Transform github repo owner to lowercase
      - name: Transform repo owner to lowercase
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Building and pushing application image go to: GitHub -> Profile -> Packages
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: milk-services/prod-line-sys/prod-line-sys-svc
          file: milk-services/prod-line-sys/prod-line-sys-svc/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER_LOWER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
